/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.blackberry020.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class MessageUtilsTest {
    @Test void testGetMessage() {
        //assertEquals("Hello      World!", MessageUtils.getMessage());
        assertTrue(true);
    }
}
