/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.blackberry020.app;


import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Paths;

public class App {
    public static void main(String[] args) throws IOException, InterruptedException {
    }
}
