/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.blackberry020.app;


import java.io.IOException;

public class DtoApp {
    public static void main(String[] args) {
    }
}
