/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.blackberry020.app;


import com.fasterxml.jackson.databind.ObjectMapper;
import org.blackberry020.app.dto.CalculateRequest;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.ArrayList;

public class ClientApp {

    public static void main(String[] args) throws Exception {

        BufferedReader consoleReader = new BufferedReader(new InputStreamReader(System.in));

        System.out.println("Enter the name of file that contains an algebraic expression");
        //String fileName = consoleReader.readLine();
        String fileName = "input.txt";

        CalculateRequest restRequest = new CalculateRequest(
                fileName, new ArrayList<>()
        );

        ObjectMapper objectMapper = new ObjectMapper();
        String json = objectMapper.writeValueAsString(restRequest);

        try {
            HttpClient client = HttpClient.newHttpClient();
            //String json = new String(Files.readAllBytes(Paths.get("example.json")));

            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create("http://localhost:8080/calculator/calculate/"))
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(json))
                    .build();

            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

            System.out.println(response.body());
        } catch (Exception e) {
            System.err.printf("Meoooow: %s%n", e.getMessage());
        }
    }
}

